# Data Scientist 
### Technical Skills
- Python, SQL, R, Excel, Matlab


### Education
- PhD (Computer Science & Informatics)
- MSc (Computing)
- MBA (International Management)
- MBA (Marketing & Finance)

### Professional Certifications

- Executive General Management 
- International Key Accounts & Supply Chain Management (Nestle Switzerland, Nestle Bangkok)
- Professional Certificates

### Portfolio
- A
- B
- C
