title: M. Usman
#logo: /assets/img/tu.png
description: Seasoned Data Sciencce Professional
#show_downloads: true
#theme: jekyll-theme-minimal
#theme: jekyll-theme-dinky # Option No.2 for theme.
theme: jekyll-theme-hacker
#theme: jekyll-theme-merlot
#theme: jekyll-theme-modernist 
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile # Modernist is the best so far.
#theme: jekyll-theme-time-machine
